# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.4
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_rgb_led_strip', [dirname(__file__)])
        except ImportError:
            import _rgb_led_strip
            return _rgb_led_strip
        if fp is not None:
            try:
                _mod = imp.load_module('_rgb_led_strip', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _rgb_led_strip = swig_import_helper()
    del swig_import_helper
else:
    import _rgb_led_strip
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class intArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, intArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, intArray, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _rgb_led_strip.new_intArray(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _rgb_led_strip.delete_intArray
    __del__ = lambda self : None;
    def __getitem__(self, *args): return _rgb_led_strip.intArray___getitem__(self, *args)
    def __setitem__(self, *args): return _rgb_led_strip.intArray___setitem__(self, *args)
    def cast(self): return _rgb_led_strip.intArray_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _rgb_led_strip.intArray_frompointer
    if _newclass:frompointer = staticmethod(_rgb_led_strip.intArray_frompointer)
intArray_swigregister = _rgb_led_strip.intArray_swigregister
intArray_swigregister(intArray)

def intArray_frompointer(*args):
  return _rgb_led_strip.intArray_frompointer(*args)
intArray_frompointer = _rgb_led_strip.intArray_frompointer


def mmio_read(*args):
  return _rgb_led_strip.mmio_read(*args)
mmio_read = _rgb_led_strip.mmio_read

def mmio_write(*args):
  return _rgb_led_strip.mmio_write(*args)
mmio_write = _rgb_led_strip.mmio_write

def mmiof_init(*args):
  return _rgb_led_strip.mmiof_init(*args)
mmiof_init = _rgb_led_strip.mmiof_init

def mmiof_read(*args):
  return _rgb_led_strip.mmiof_read(*args)
mmiof_read = _rgb_led_strip.mmiof_read

def mmiof_write(*args):
  return _rgb_led_strip.mmiof_write(*args)
mmiof_write = _rgb_led_strip.mmiof_write

def mmiof_close(*args):
  return _rgb_led_strip.mmiof_close(*args)
mmiof_close = _rgb_led_strip.mmiof_close

def init():
  return _rgb_led_strip.init()
init = _rgb_led_strip.init

def ws2801_send_buffer(*args):
  return _rgb_led_strip.ws2801_send_buffer(*args)
ws2801_send_buffer = _rgb_led_strip.ws2801_send_buffer

def ws2812_send_buffer(*args):
  return _rgb_led_strip.ws2812_send_buffer(*args)
ws2812_send_buffer = _rgb_led_strip.ws2812_send_buffer

def ws2812_send_bit(*args):
  return _rgb_led_strip.ws2812_send_bit(*args)
ws2812_send_bit = _rgb_led_strip.ws2812_send_bit
# This file is compatible with both classic and new-style classes.


